### PR TITLE
fix(create-initial-pr): detect dependency updates for messages #677

### LINKED ISSUE #677: Messages in issues, PRs and comments: various issues
For the initial PR in a monorepo where the root `package.json` does not need updates, but others do:

- [x] The PR title is "Add Greenkeeper Badge", which is incorrect
- [x] If the root level `package.json` is up to date, the PR message is that _everything_ is up to date, which is not necessarily the case
- [x] The repo name in the first sentence of an initial PR should be in backticks (actually, wherever we mention the repo by name, wrap it in backticks)

### PR DESCRIPTION
**Pull request by janl**
Closes #677

### CODE REVIEW

File: test/jobs/create-initial-branch.js [hunk 1]
```diff
@@ -567,6 +568,181 @@ describe('create initial branch', () => {
     })
   })
 
+  test.only('#667 PR message with no root package.json update', async () => {
```
Comment (espy) [inline test/jobs/create-initial-branch.js]: `.only`, and it’s 677
