### PR TITLE
fix(repo-docs): allow initial branch to continue with config file errors

### LINKED ISSUE #691: Bug: resetting a monorepo with an invalid greenkeeper.json doesn’t work
Resetting runs `create-initial-branch` twice, registers the parse error twice, but does not open an issue. 

single reset fires two initial branches

### PR DESCRIPTION
**Pull request by espy**
This should fix #691 

The issue was that when the `greenkeeper.json` is invalid, we don’t return an empty object out of `get-files.js`, but an error. One level up, we then leave `greenkeeperConfigFile` undefined, which prevents everything else from happening.

### CODE REVIEW

File: jobs/create-initial-branch.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ module.exports = async function ({ repositoryId, closes = [] }) {
     if (e.name && e.name === 'GKConfigFileParseError') {
       log.warn('create initial branch failed because of an invalid config file')
       // We set a flag that the config was borked. When the next push for the greenkeeper.json comes and it is valid
-      // we can tell by the flag whether we still need to open the initial PR that we didn’t do here.
+      // we can tell by the flag whether we still nee2d to open the initial PR that we didn’t do here.
```
Comment (Realtin) [inline jobs/create-initial-branch.js]: :D
